---
title: "Grand Sumo Tournament Matchups"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Author", href: "https://github.com/Cervus1983" }
    source_code: embed
runtime: shiny
---

```{r}
# libraries + plot.basho(df)
source("plot.basho.R")
```

```{r}
library(httr)
library(flexdashboard)
library(shiny)
```

```{r}
# rank (e.g. "Y1e") to division ("Makuuchi")
get_division <- function(x) recode(
	str_match(x,"^\\D+"),
	"Y" = "Makuuchi",
	"O" = "Makuuchi",
	"S" = "Makuuchi",
	"K" = "Makuuchi",
	"M" = "Makuuchi",
	"J" = "Juryo",
	"Ms" = "Makushita",
	"Sd" = "Sandanme",
	"Jd" = "Jonidan",
	"Jk" = "Jonokuchi",
	"Mz" = "Mae-zumo"
)
```

```{r}
# fetch data from GitHub repository: Cervus1983/sumodb
response <- GET("https://api.github.com/repos/Cervus1983/sumodb/git/trees/96fe177573c8268e263dde4ff41528450a003f4c")

if(response$status_code == 200) {
	tree <- content(response)$tree
	path <- sapply(tree, function(x) x$path)
	basho <- str_match(path, "([0-9]{4}\\.[0-9]{2})\\.results\\.csv")[, 2] %>% na.omit()
}
```


Column {.sidebar}
-----------------------------------------------------------------------

&nbsp;

```{r}
renderUI({
	req(basho)

	selectInput(
		inputId = "year_month",
		label =  NULL,
		choices = basho %>% 
			set_names(
				paste(
					basho %>% substr(1, 4),
					basho %>% substr(6, 7) %>% as.integer() %>% month.name[.]
				)
			) %>% rev()
	)
})
```

15 days of [Honbasho](https://en.wikipedia.org/wiki/Honbasho).<br>Only [makuuchi](https://en.wikipedia.org/wiki/Makuuchi).

Last day in the bottom-right corner. Playoff (e.g. in 2017 March) shown as day 16.

Bouts shown as vertical lines, left to right in the running order.

Line ends represent [rikishi](https://en.wikipedia.org/wiki/Rikishi).<br>Higher dot --- higher rank.<br>Big dot --- winner.

```{r}
data <- reactive({
	req(input$year_month)
	
	sprintf(
		"https://raw.githubusercontent.com/Cervus1983/sumodb/all-divisions/CSV/%s.results.csv",
		input$year_month
	) %>% 
		read_csv() %>% 
		# Makuuchi (top division)
		filter(get_division(rank1) == "Makuuchi" | get_division(rank2) == "Makuuchi") %>% 
		# pertinent columns
		select(basho, day, shikona1, rank1, win1, kimarite, win2, shikona2, rank2)
})
```

```{r}
output$link <- downloadHandler(
	filename = function() paste(input$year_month, "csv", sep = "."),
	content = function(filename) write_csv(data(), filename)
)
```

&nbsp;

Download data:

```{r}
renderUI({
	req(data())
	
	downloadLink(
		outputId = "link",
		label = paste(input$year_month, "csv", sep = ".")
	)
})
```


Column
-----------------------------------------------------------------------

```{r}
output$plot <- renderPlotly({
	req(data())
	
	plot.basho(data())
})
```

```{r}
plotlyOutput("plot", height = "100%")
```
