---
title: "Grand Sumo Tournament Matchups"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Author", href: "https://github.com/Cervus1983" }
    source_code: embed
runtime: shiny
---

```{r}
# libraries + plot.basho(df)
source("plot.basho.R")
```

```{r}
library(httr)
library(flexdashboard)
library(shiny)
```

```{r}
all_data <- "data.csv" %>% 
	read_csv() %>% 
	# remove 'mirror' records
	filter(rikishi1_id < rikishi2_id)
```

```{r}
# rank (e.g. "Y1e") to division ("Makuuchi")
get_division <- function(x) recode(
	str_match(x,"^\\D+"),
	"Y" = "Makuuchi",
	"O" = "Makuuchi",
	"S" = "Makuuchi",
	"K" = "Makuuchi",
	"M" = "Makuuchi",
	"J" = "Juryo",
	"Ms" = "Makushita",
	"Sd" = "Sandanme",
	"Jd" = "Jonidan",
	"Jk" = "Jonokuchi",
	"Mz" = "Mae-zumo"
)
```

Column {.sidebar}
-----------------------------------------------------------------------

&nbsp;

```{r}
renderUI({
	basho <- all_data %>% 
		pull(basho) %>% 
		unique()
	
	selectInput(
		inputId = "year_month",
		label =  NULL,
		choices = basho %>% 
			set_names(
				paste(
					basho %>% substr(1, 4),
					basho %>% substr(6, 7) %>% as.integer() %>% month.name[.]
				)
			) %>% 
			rev()
	)
})
```

15 days of [Honbasho](https://en.wikipedia.org/wiki/Honbasho).<br>Only [makuuchi](https://en.wikipedia.org/wiki/Makuuchi).

Last day in the bottom-right corner. Playoff (e.g. in 2017 March) shown as day 16.

Bouts shown as vertical lines, left to right in the running order.

Line ends represent [rikishi](https://en.wikipedia.org/wiki/Rikishi).<br>Higher dot --- higher rank.<br>Big dot --- winner.

```{r}
data <- reactive({
	req(input$year_month)
	
	all_data %>% 
		filter(
			# selected basho
			basho == input$year_month,
			# makuuchi
			get_division(rikishi1_rank) == "Makuuchi" | get_division(rikishi2_rank) == "Makuuchi"
		) %>% 
		# pertinent columns
		select(basho, day, rikishi1_shikona, rikishi1_rank, rikishi1_win, kimarite, rikishi2_win, rikishi2_shikona, rikishi2_rank)
})
```

```{r}
output$link <- downloadHandler(
	filename = function() paste(input$year_month, "csv", sep = "."),
	content = function(filename) write_csv(data(), filename)
)
```

&nbsp;

Download data:

```{r}
renderUI({
	req(data())
	
	downloadLink(
		outputId = "link",
		label = paste(input$year_month, "csv", sep = ".")
	)
})
```


Column
-----------------------------------------------------------------------

```{r}
output$plot <- renderPlotly({
	req(data())
	
	plot.basho(data())
})
```

```{r}
plotlyOutput("plot", height = "100%")
```
